import path from 'node:path';
import type { TypstCompileResult } from './types.js';

/**
 * Emit a self-contained ESM React page module from a Typst compile result.
 * Uses `react/jsx-runtime` so the output does not need a second JSX transform.
 */
export function generateTypstPageModule(
  result: TypstCompileResult,
  className: string,
): string {
  const frontmatter = {
    ...result.frontmatter,
    title: result.title,
    ...(result.description ? { description: result.description } : {}),
  };

  const metaKey = path.basename(result.filepath);
  const pageMeta = {
    toc: result.toc,
    title: result.title,
    headingTitle: result.title,
    description: result.description,
    frontmatter,
  };

  return `/* Auto-generated by rspress-plugin-typst — do not edit */
import { jsx as _jsx } from 'react/jsx-runtime';
import { TypstDoc } from 'rspress-plugin-typst/runtime';

export const frontmatter = ${JSON.stringify(frontmatter, null, 2)};

const __typstBody = ${JSON.stringify(result.body)};
const __typstToc = ${JSON.stringify(result.toc)};
const __typstPageMeta = ${JSON.stringify(pageMeta, null, 2)};

export default function TypstPage() {
  return _jsx(TypstDoc, {
    html: __typstBody,
    className: ${JSON.stringify(className)},
    toc: __typstToc,
  });
}

TypstPage.__RSPRESS_PAGE_META = {};
TypstPage.__RSPRESS_PAGE_META[${JSON.stringify(metaKey)}] = __typstPageMeta;
`;
}
